# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rustopt_wrappers", use_symbols = TRUE, package_name = "rustopt")

#' @docType package
#' @usage NULL
#' @useDynLib rustopt, .registration = TRUE
NULL

gen_opt <- function(po_1_t, po_1_c, po_2_t, po_2_c, n_treat, n_iter, temperature_decay) .Call(wrap__gen_opt, po_1_t, po_1_c, po_2_t, po_2_c, n_treat, n_iter, temperature_decay)

